on: pull_request
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        env:
          DEFAULT_BRANCH: master
          REACT_APP_DOCUMENT_TITLE: rhbp
          REACT_APP_API_BASE_URL: http://localhost:3001
      - run: |
          npm i
          npm run lint -- --fix src/
          npm run format -- -c src/
          npm run coverage
          npm start &
          npm run api &
          npm run e2e -- run --headed --browser chrome
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
