on: pull_request
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        env:
          DEFAULT_BRANCH: master
          REACT_APP_API_BASE_URL: http://localhost:3001
      - run: |
          npm i
          npm run lint -- src/
          npm run format -- -c src/
          npm run coverage
      - uses: cypress-io/github-action@v2
        with:
          start: npm run start-with-api
          wait-on: "http://localhost:3000"
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
